# fly.toml app configuration file generated for insightedge-core-prod on 2023-05-08T17:21:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insightedge-core-prod"
primary_region = "sea"

[build]
image = "node:18-bullseye"
include_dirs = ["dist"]
cmd = "npm ci && npm run build"

[deploy]
release_command = "npm ci && npm run start:prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
NODE_ENV = "production"